package com.competitive.ai;

import com.competitive.model.Problem;
import com.competitive.model.Testcase;
import com.competitive.model.SampleCode;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * Parse AI responses (JSON, markdown) thành Java objects.
 * Xử lý cả JSON thuần và JSON wrapped trong markdown code blocks.
 * 
 * @author Nguyễn Thành Huy
 * @version 1.0
 */
public class ResponseParser {
    
    private static final ObjectMapper mapper = new ObjectMapper();
    
    /**
     * Simple class to hold test input data (without expected output).
     * Used for verification workflow where expected outputs are generated by running AC code.
     */
    public static class TestInput {
        private int id;
        private String input;
        private String description;
        private String type;
        
        public TestInput() {}
        
        public TestInput(int id, String input, String description, String type) {
            this.id = id;
            this.input = input;
            this.description = description;
            this.type = type;
        }
        
        public int getId() { return id; }
        public void setId(int id) { this.id = id; }
        
        public String getInput() { return input; }
        public void setInput(String input) { this.input = input; }
        
        public String getDescription() { return description; }
        public void setDescription(String description) { this.description = description; }
        
        public String getType() { return type; }
        public void setType(String type) { this.type = type; }
    }
    
    // ===== 1. PARSE PROBLEM ANALYSIS =====
    
    /**
     * Parse JSON response từ AI thành Problem object.
     * 
     * @param response raw response từ AI (có thể là JSON thuần hoặc wrapped trong markdown)
     * @return Problem object với các fields đã được populate
     * @throws IOException nếu response không hợp lệ hoặc thiếu required fields
     */
    public static Problem parseProblemAnalysis(String response) throws IOException {
        if (response == null || response.isBlank()) {
            throw new IOException("ResponseParser parseProblemAnalysis: Response is empty");
        }
        
        // DEBUG: Log raw response (first 2000 chars)
        System.err.println("=== DEBUG: Raw AI Response for Problem Analysis (first 2000 chars) ===");
        System.err.println(response.substring(0, Math.min(response.length(), 2000)));
        System.err.println("=== Total length: " + response.length() + " chars ===");
        System.err.println("=== END DEBUG ===");
        
        // Extract JSON từ response (xử lý markdown code blocks)
        String cleanJson = extractJsonFromResponse(response);
        
        // DEBUG: Log cleaned JSON (first 2000 chars)
        System.err.println("=== DEBUG: Cleaned JSON (first 2000 chars) ===");
        System.err.println(cleanJson.substring(0, Math.min(cleanJson.length(), 2000)));
        System.err.println("=== Total length: " + cleanJson.length() + " chars ===");
        System.err.println("=== END DEBUG ===");
        
        if (!isValidJson(cleanJson)) {
            throw new IOException("ResponseParser parseProblemAnalysis: Invalid JSON format - " + 
                                  "Response may be incomplete or malformed");
        }
        
        try {
            JsonNode root = mapper.readTree(cleanJson);
            
            Problem problem = new Problem();
            
            // Parse các fields (hỗ trợ nhiều tên field khác nhau từ AI)
            problem.setTitle(getStringField(root, "title", "name", "problemName"));
            problem.setStatement(getStringField(root, "statement", "description", "problemStatement", "full_statement"));
            problem.setInputFormat(getStringField(root, "inputFormat", "input_format", "input"));
            problem.setOutputFormat(getStringField(root, "outputFormat", "output_format", "output"));
            problem.setConstraints(getStringField(root, "constraints", "constraint"));
            
            // Time limit - với validation linh hoạt
            String timeLimit = getStringField(root, "timeLimit", "time_limit", "timeLimitMs");
            if (timeLimit != null && !timeLimit.isBlank()) {
                // Normalize và check format
                String normalized = timeLimit.replaceAll("\\s+", "").toLowerCase();
                if (normalized.matches("\\d+(\\.\\d+)?(ms|s)?")) {
                    problem.setTimeLimit(timeLimit);
                } else {
                    // Format không hợp lệ, dùng default
                    problem.setTimeLimit("1s");
                }
            } else {
                problem.setTimeLimit("1s"); // Default nếu null hoặc blank
            }
            
            // Memory limit - với validation linh hoạt
            String memoryLimit = getStringField(root, "memoryLimit", "memory_limit");
            if (memoryLimit != null && !memoryLimit.isBlank()) {
                // Normalize và check format
                String normalized = memoryLimit.replaceAll("\\s+", "").toUpperCase();
                if (normalized.matches("\\d+MB")) {
                    problem.setMemoryLimit(memoryLimit);
                } else {
                    // Format không hợp lệ, dùng default
                    problem.setMemoryLimit("256MB");
                }
            } else {
                problem.setMemoryLimit("256MB"); // Default nếu null hoặc blank
            }
            
            // Optional fields
            String contestType = getStringField(root, "problemType", "contestType", "contest_type", "type");
            if (contestType != null) {
                problem.setContestType(contestType);
            }
            
            String examples = getStringField(root, "examples", "sampleIO", "sample_io");
            if (examples != null) {
                problem.setExamples(examples);
            }
            
            // Validate required fields
            validateProblemFields(problem);
            
            return problem;
            
        } catch (Exception e) {
            throw new IOException("ResponseParser parseProblemAnalysis: Failed to parse JSON - " + 
                                  e.getMessage() + " - AI response may be incomplete", e);
        }
    }
    
    /**
     * Validate rằng Problem object có đủ required fields.
     * Với ảnh, cho phép thiếu một số field và tự động điền giá trị mặc định.
     */
    private static void validateProblemFields(Problem problem) throws IOException {
        List<String> missingFields = new ArrayList<>();
        
        if (problem.getTitle() == null || problem.getTitle().isBlank()) {
            missingFields.add("title");
        }
        if (problem.getStatement() == null || problem.getStatement().isBlank()) {
            missingFields.add("statement");
        }
        
        // Cho phép thiếu inputFormat/outputFormat (có thể suy luận từ statement)
        if (problem.getInputFormat() == null || problem.getInputFormat().isBlank()) {
            problem.setInputFormat("Xem mô tả bài toán");
        }
        if (problem.getOutputFormat() == null || problem.getOutputFormat().isBlank()) {
            problem.setOutputFormat("Xem mô tả bài toán");
        }
        
        if (!missingFields.isEmpty()) {
            throw new IOException("ResponseParser parseProblemAnalysis: Missing required fields: " + 
                                  String.join(", ", missingFields) + " - AI response may be incomplete");
        }
    }
    
    // ===== 2. PARSE TEST CASES =====
    
    /**
     * Parse JSON array response thành List<Testcase>.
     * 
     * @param response raw response từ AI (JSON array)
     * @return List of Testcase objects
     * @throws IOException nếu response không hợp lệ
     */
    public static List<Testcase> parseTestcases(String response) throws IOException {
        if (response == null || response.isBlank()) {
            throw new IOException("ResponseParser parseTestcases: Response is empty");
        }
        
        // DEBUG: Log raw response (first 1000 chars)
        System.err.println("=== DEBUG: Raw AI Response (first 1000 chars) ===");
        System.err.println(response.substring(0, Math.min(response.length(), 1000)));
        System.err.println("=== END DEBUG ===");
        
        String cleanJson = extractJsonFromResponse(response);
        
        // DEBUG: Log cleaned JSON (first 1000 chars)
        System.err.println("=== DEBUG: Cleaned JSON (first 1000 chars) ===");
        System.err.println(cleanJson.substring(0, Math.min(cleanJson.length(), 1000)));
        System.err.println("=== END DEBUG ===");
        
        // Try to fix common JSON issues
        if (!isValidJson(cleanJson)) {
            System.err.println("=== DEBUG: JSON invalid, attempting auto-fix ===");
            
            // Common issue 1: Trailing comma before closing bracket
            String fixed = cleanJson.replaceAll(",\\s*]", "]").replaceAll(",\\s*}", "}");
            
            // Common issue 2: Missing closing bracket
            if (!fixed.trim().endsWith("]") && !fixed.trim().endsWith("}")) {
                if (fixed.trim().startsWith("[")) {
                    fixed = fixed.trim() + "]";
                } else if (fixed.trim().startsWith("{")) {
                    fixed = fixed.trim() + "}";
                }
            }
            
            // Common issue 3: Unescaped newlines in strings (should be \\n)
            // This is tricky - only fix if it's clearly wrong
            
            if (isValidJson(fixed)) {
                System.err.println("=== DEBUG: Auto-fix successful ===");
                cleanJson = fixed;
            } else {
                System.err.println("=== DEBUG: Auto-fix failed ===");
            }
        }
        
        if (!isValidJson(cleanJson)) {
            // Try to recover from truncated JSON (common when AI hits max_tokens)
            // Strategy: find the last complete JSON object and close the array
            System.err.println("=== DEBUG: Attempting truncated JSON recovery ===");
            
            String recovered = tryRecoverTruncatedJsonArray(cleanJson);
            if (recovered != null && isValidJson(recovered)) {
                System.err.println("=== DEBUG: Truncated JSON recovery successful ===");
                cleanJson = recovered;
            } else {
                // Provide more detailed error message
                String preview = cleanJson.length() > 200 ? cleanJson.substring(0, 200) + "..." : cleanJson;
                String endPreview = cleanJson.length() > 200 ? "..." + cleanJson.substring(cleanJson.length() - 200) : cleanJson;
                
                // Try to parse and get actual error
                String parseError = "Unknown";
                try {
                    mapper.readTree(cleanJson);
                } catch (Exception e) {
                    parseError = e.getMessage();
                }
                
                throw new IOException("ResponseParser parseTestcases: Invalid JSON format. " +
                                      "Parse error: " + parseError + "\n" +
                                      "Preview (start): " + preview + "\n" +
                                      "Preview (end): " + endPreview + "\n" +
                                      "Full response length: " + response.length() + " chars. " +
                                      "Cleaned JSON length: " + cleanJson.length() + " chars.");
            }
        }
        
        try {
            JsonNode root = mapper.readTree(cleanJson);
            
            if (!root.isArray()) {
                throw new IOException("ResponseParser parseTestcases: Expected JSON array but got object");
            }
            
            List<Testcase> testcases = new ArrayList<>();
            
            for (int i = 0; i < root.size(); i++) {
                JsonNode tcNode = root.get(i);
                
                Testcase tc = new Testcase();
                
                // ID (có thể từ AI hoặc tự generate)
                if (tcNode.has("id")) {
                    tc.setId(tcNode.get("id").asInt());
                } else {
                    tc.setId(i + 1);
                }
                
                // Input (required)
                String input = getStringField(tcNode, "input", "testInput", "in");
                if (input == null || input.isBlank()) {
                    throw new IOException("ResponseParser parseTestcases: Missing 'input' field in test case #" + (i + 1));
                }
                tc.setInput(input);
                
                // Expected Output (optional - AI có thể thiếu field này)
                String expectedOutput = getStringField(tcNode, "expectedOutput", "expected_output", 
                                                       "output", "expectedResult", "answer");
                if (expectedOutput == null || expectedOutput.isBlank()) {
                    // Nếu thiếu expectedOutput, dùng placeholder
                    // User sẽ cần verify test case này manually hoặc dùng verification workflow
                    System.err.println("=== WARNING: Test case #" + (i + 1) + " missing expectedOutput. Using placeholder. ===");
                    expectedOutput = "[MISSING - Please verify manually]";
                }
                tc.setExpectedOutput(expectedOutput);
                
                // Note (optional)
                String note = getStringField(tcNode, "note", "description", "type", "comment");
                if (note != null) {
                    tc.setNote(note);
                }
                
                // Mark as AI-generated
                tc.setGenerated(true);
                
                testcases.add(tc);
            }
            
            if (testcases.isEmpty()) {
                throw new IOException("ResponseParser parseTestcases: No test cases found in response");
            }
            
            return testcases;
            
        } catch (IOException e) {
            throw e; // Re-throw our custom IOExceptions
        } catch (Exception e) {
            throw new IOException("ResponseParser parseTestcases: Failed to parse JSON - " + 
                                  e.getMessage(), e);
        }
    }
    
    /**
     * Parse JSON response từ AI thành List of TestInput (KHÔNG có expected output).
     * Dùng cho verification workflow: AI sinh inputs, sau đó run AC code để lấy expected output.
     * 
     * @param response raw response từ AI (có thể là JSON thuần hoặc wrapped trong markdown)
     * @return List of TestInput objects (chỉ có input, không có expected output)
     * @throws IOException nếu response không hợp lệ
     */
    public static List<TestInput> parseTestInputsOnly(String response) throws IOException {
        if (response == null || response.isBlank()) {
            throw new IOException("ResponseParser parseTestInputsOnly: Response is empty");
        }
        
        // DEBUG: Log raw response (first 1000 chars)
        System.err.println("=== DEBUG: Raw AI Response for Test Inputs (first 1000 chars) ===");
        System.err.println(response.substring(0, Math.min(response.length(), 1000)));
        System.err.println("=== END DEBUG ===");
        
        String cleanJson = extractJsonFromResponse(response);
        
        // DEBUG: Log cleaned JSON (first 1000 chars)
        System.err.println("=== DEBUG: Cleaned JSON for Test Inputs (first 1000 chars) ===");
        System.err.println(cleanJson.substring(0, Math.min(cleanJson.length(), 1000)));
        System.err.println("=== END DEBUG ===");
        
        // Try to fix common JSON issues
        if (!isValidJson(cleanJson)) {
            System.err.println("=== DEBUG: JSON invalid, attempting auto-fix ===");
            
            // Common issue 1: Trailing comma before closing bracket
            String fixed = cleanJson.replaceAll(",\\s*]", "]").replaceAll(",\\s*}", "}");
            
            // Common issue 2: Missing closing bracket
            if (!fixed.trim().endsWith("]") && !fixed.trim().endsWith("}")) {
                if (fixed.trim().startsWith("[")) {
                    fixed = fixed.trim() + "]";
                } else if (fixed.trim().startsWith("{")) {
                    fixed = fixed.trim() + "}";
                }
            }
            
            if (isValidJson(fixed)) {
                System.err.println("=== DEBUG: Auto-fix successful ===");
                cleanJson = fixed;
            } else {
                System.err.println("=== DEBUG: Auto-fix failed ===");
            }
        }
        
        if (!isValidJson(cleanJson)) {
            // Provide more detailed error message
            String preview = cleanJson.length() > 200 ? cleanJson.substring(0, 200) + "..." : cleanJson;
            String endPreview = cleanJson.length() > 200 ? "..." + cleanJson.substring(cleanJson.length() - 200) : cleanJson;
            
            // Try to parse and get actual error
            String parseError = "Unknown";
            try {
                mapper.readTree(cleanJson);
            } catch (Exception e) {
                parseError = e.getMessage();
            }
            
            throw new IOException("ResponseParser parseTestInputsOnly: Invalid JSON format. " +
                                  "Parse error: " + parseError + "\n" +
                                  "Preview (start): " + preview + "\n" +
                                  "Preview (end): " + endPreview + "\n" +
                                  "Full response length: " + response.length() + " chars. " +
                                  "Cleaned JSON length: " + cleanJson.length() + " chars.");
        }
        
        try {
            JsonNode root = mapper.readTree(cleanJson);
            
            if (!root.isArray()) {
                throw new IOException("ResponseParser parseTestInputsOnly: Expected JSON array but got object");
            }
            
            List<TestInput> testInputs = new ArrayList<>();
            
            for (int i = 0; i < root.size(); i++) {
                JsonNode inputNode = root.get(i);
                
                TestInput testInput = new TestInput();
                
                // ID (có thể từ AI hoặc tự generate)
                if (inputNode.has("id")) {
                    testInput.setId(inputNode.get("id").asInt());
                } else {
                    testInput.setId(i + 1);
                }
                
                // Input (required)
                String input = getStringField(inputNode, "input", "testInput", "in");
                if (input == null || input.isBlank()) {
                    throw new IOException("ResponseParser parseTestInputsOnly: Missing 'input' field in test input #" + (i + 1));
                }
                
                // Validate input length (max 500 chars)
                if (input.length() > 500) {
                    throw new IOException("ResponseParser parseTestInputsOnly: Input #" + (i + 1) + 
                                          " exceeds 500 character limit (" + input.length() + " chars). " +
                                          "Please reduce input size (e.g., reduce n from 1000 to 50-100).");
                }
                
                testInput.setInput(input);
                
                // Description (optional)
                String description = getStringField(inputNode, "description", "note", "comment");
                if (description != null) {
                    testInput.setDescription(description);
                }
                
                // Type (optional)
                String type = getStringField(inputNode, "type", "testType", "category");
                if (type != null) {
                    testInput.setType(type);
                } else {
                    testInput.setType("NORMAL"); // Default type
                }
                
                // Verify that expectedOutput field is NOT present (this is inputs-only)
                if (inputNode.has("expectedOutput") || inputNode.has("expected_output") || 
                    inputNode.has("output") || inputNode.has("answer")) {
                    System.err.println("=== WARNING: Test input #" + (i + 1) + 
                                       " contains expectedOutput field. This should be inputs-only. Ignoring expectedOutput. ===");
                }
                
                testInputs.add(testInput);
            }
            
            if (testInputs.isEmpty()) {
                throw new IOException("ResponseParser parseTestInputsOnly: No test inputs found in response");
            }
            
            System.err.println("=== DEBUG: Successfully parsed " + testInputs.size() + " test inputs ===");
            
            return testInputs;
            
        } catch (IOException e) {
            throw e; // Re-throw our custom IOExceptions
        } catch (Exception e) {
            throw new IOException("ResponseParser parseTestInputsOnly: Failed to parse JSON - " + 
                                  e.getMessage(), e);
        }
    }
    
    // ===== 3. PARSE CHECKER CODE =====
    
    /**
     * Parse checker code từ response (có thể là plain text hoặc markdown).
     * 
     * @param response raw response từ AI
     * @return checker code (Java source code)
     * @throws IOException nếu không extract được code
     */
    public static String parseCheckerCode(String response) throws IOException {
        if (response == null || response.isBlank()) {
            throw new IOException("ResponseParser parseCheckerCode: Response is empty");
        }
        
        String code = extractCodeFromResponse(response);
        
        // Validate code contains expected patterns
        if (!code.contains("class") || !code.contains("check")) {
            throw new IOException("ResponseParser parseCheckerCode: Code validation failed - " +
                                  "Missing 'class' or 'check' method. Code may be incomplete.");
        }
        
        return code;
    }
    
    // ===== 4. PARSE SAMPLE CODE =====
    
    /**
     * Parse sample code từ response thành SampleCode object.
     * 
     * @param response raw response từ AI
     * @param type loại code (AC, WA, TLE)
     * @param language ngôn ngữ lập trình
     * @return SampleCode object
     * @throws IOException nếu không extract được code
     */
    public static SampleCode parseSampleCode(String response, SampleCode.CodeType type, 
                                             SampleCode.Language language) throws IOException {
        if (response == null || response.isBlank()) {
            throw new IOException("ResponseParser parseSampleCode: Response is empty");
        }
        
        String code = extractCodeFromResponse(response);
        
        // Validate code contains expected patterns based on language
        boolean isValid = false;
        
        if (language == SampleCode.Language.CPP) {
            // C++ validation: check for #include and int main()
            boolean hasInclude = code.contains("#include");
            boolean hasMain = code.contains("int main()") || code.contains("int main(") || 
                             code.contains("int main (");
            isValid = hasInclude && hasMain;
        } else if (language == SampleCode.Language.JAVA) {
            // Java validation: check for class and main method
            boolean hasClass = code.contains("class Main") || code.contains("class Solution") || 
                              code.contains("public class") || code.contains("class ");
            boolean hasMain = code.contains("public static void main") || code.contains("void main");
            isValid = hasClass && hasMain;
        } else if (language == SampleCode.Language.PYTHON) {
            // Python validation: just check it's not empty and has some code structure
            isValid = code.contains("def ") || code.contains("if ") || code.contains("for ") || 
                     code.contains("while ") || code.contains("print(") || code.contains("input(");
        } else {
            // Unknown language - accept if not empty
            isValid = !code.trim().isEmpty();
        }
        
        if (!isValid) {
            // Try to provide more helpful error message
            String preview = code.length() > 100 ? code.substring(0, 100) + "..." : code;
            String expectedPattern = switch (language) {
                case CPP -> "#include and int main()";
                case JAVA -> "class and main method";
                case PYTHON -> "Python code structure (def, if, for, etc.)";
                default -> "valid code";
            };
            throw new IOException("ResponseParser parseSampleCode: Code validation failed - " +
                                  "Missing " + expectedPattern + ". Code may be incomplete or malformed. " +
                                  "Preview: " + preview);
        }
        
        SampleCode sampleCode = new SampleCode(type, language, code);
        
        // Extract explanation from comments if present
        String explanation = extractExplanationFromCode(code, type);
        if (explanation != null) {
            sampleCode.setExplanation(explanation);
        }
        
        return sampleCode;
    }
    
    // ===== HELPER METHODS =====
    
    /**
     * Extract JSON từ response, xử lý markdown code blocks.
     * 
     * Hỗ trợ các format:
     * - Pure JSON: {"key": "value"} hoặc [...]
     * - Markdown: ```json\n{"key": "value"}\n```
     * - Markdown: ```\n{"key": "value"}\n```
     * - Text before JSON: "Here is the JSON:\n\n[...]"
     */
    private static String extractJsonFromResponse(String response) {
        String cleaned = response.trim();
        
        // Case 1: Remove markdown code blocks FIRST (most common issue)
        if (cleaned.contains("```")) {
            // Find ALL code blocks and extract the largest one (likely the JSON)
            int firstBacktick = cleaned.indexOf("```");
            int lastBacktick = cleaned.lastIndexOf("```");
            
            if (firstBacktick != -1 && lastBacktick != -1 && firstBacktick < lastBacktick) {
                String betweenBackticks = cleaned.substring(firstBacktick + 3, lastBacktick);
                
                // Remove language identifier if present (json, javascript, etc.)
                betweenBackticks = betweenBackticks.trim();
                String lowerBetween = betweenBackticks.toLowerCase();
                
                // Check for language identifiers on first line
                String[] langIdentifiers = {"json", "javascript", "js"};
                for (String lang : langIdentifiers) {
                    if (lowerBetween.startsWith(lang)) {
                        int firstNewline = betweenBackticks.indexOf('\n');
                        if (firstNewline != -1) {
                            betweenBackticks = betweenBackticks.substring(firstNewline + 1);
                        }
                        break;
                    }
                }
                
                cleaned = betweenBackticks.trim();
            }
        }
        
        // Case 2: Remove common text prefixes before JSON
        String[] commonPrefixes = {
            "Here is the JSON:",
            "Here's the JSON:",
            "The JSON is:",
            "JSON:",
            "Đây là JSON:",
            "JSON như sau:",
            "Dưới đây là JSON:",
            "Response:",
            "Output:"
        };
        
        for (String prefix : commonPrefixes) {
            if (cleaned.toLowerCase().startsWith(prefix.toLowerCase())) {
                cleaned = cleaned.substring(prefix.length()).trim();
                break;
            }
        }
        
        // Case 3: Find JSON start ([ or {) - most reliable
        int jsonStart = -1;
        for (int i = 0; i < Math.min(cleaned.length(), 2000); i++) {
            char c = cleaned.charAt(i);
            if (c == '[' || c == '{') {
                jsonStart = i;
                break;
            }
        }
        
        if (jsonStart > 0) {
            cleaned = cleaned.substring(jsonStart);
        } else if (jsonStart == -1) {
            // No JSON found at all - return as is and let validation fail
            return cleaned;
        }
        
        // Case 4: Find JSON end (] or }) using bracket matching
        // This is more robust than just finding the last bracket
        int depth = 0;
        char startChar = cleaned.charAt(0); // Should be [ or {
        char endChar = (startChar == '[') ? ']' : '}';
        boolean inString = false;
        boolean escaped = false;
        int jsonEnd = -1;
        
        for (int i = 0; i < cleaned.length(); i++) {
            char c = cleaned.charAt(i);
            
            // Handle string escaping
            if (escaped) {
                escaped = false;
                continue;
            }
            
            if (c == '\\') {
                escaped = true;
                continue;
            }
            
            // Handle strings (don't count brackets inside strings)
            if (c == '"') {
                inString = !inString;
                continue;
            }
            
            if (inString) {
                continue;
            }
            
            // Count bracket depth
            if (c == startChar) {
                depth++;
            } else if (c == endChar) {
                depth--;
                if (depth == 0) {
                    jsonEnd = i + 1;
                    break;
                }
            }
        }
        
        if (jsonEnd > 0 && jsonEnd <= cleaned.length()) {
            cleaned = cleaned.substring(0, jsonEnd);
        }
        
        // Case 5: Remove any trailing text after JSON
        // Sometimes AI adds explanatory text after the JSON
        cleaned = cleaned.trim();
        
        return cleaned;
    }
    
    /**
     * Extract code từ response, xử lý markdown code blocks.
     * 
     * Hỗ trợ các format:
     * - Plain code: public class Solution { }
     * - Markdown: ```java\npublic class Solution { }\n```
     * - Markdown: ```\npublic class Solution { }\n```
     * - Text before code: "Here is the code:\n\npublic class Solution { }"
     */
    private static String extractCodeFromResponse(String response) throws IOException {
        String cleaned = response.trim();
        
        // Case 1: Remove markdown code blocks
        if (cleaned.contains("```")) {
            // Find first ``` and last ```
            int firstBacktick = cleaned.indexOf("```");
            int lastBacktick = cleaned.lastIndexOf("```");
            
            if (firstBacktick != -1 && lastBacktick != -1 && firstBacktick < lastBacktick) {
                // Extract content between first and last ```
                String betweenBackticks = cleaned.substring(firstBacktick + 3, lastBacktick);
                
                // Remove language identifier if present (java, cpp, python, etc.)
                betweenBackticks = betweenBackticks.trim();
                if (betweenBackticks.startsWith("java") || betweenBackticks.startsWith("cpp") || 
                    betweenBackticks.startsWith("python") || betweenBackticks.startsWith("c++")) {
                    int firstNewline = betweenBackticks.indexOf('\n');
                    if (firstNewline != -1) {
                        betweenBackticks = betweenBackticks.substring(firstNewline + 1);
                    }
                }
                
                cleaned = betweenBackticks.trim();
            }
        }
        
        // Case 2: Remove common text prefixes
        String[] commonPrefixes = {
            "Here is the code:",
            "Here's the code:",
            "The code is:",
            "Code:",
            "Solution:",
            "Đây là code:",
            "Code như sau:",
            "Giải pháp:"
        };
        
        for (String prefix : commonPrefixes) {
            if (cleaned.toLowerCase().startsWith(prefix.toLowerCase())) {
                cleaned = cleaned.substring(prefix.length()).trim();
                break;
            }
        }
        
        // Case 3: If code starts with explanatory text, try to find where actual code starts
        // Look for common Java code starting patterns
        String[] codeStartPatterns = {
            "import ",
            "package ",
            "public class ",
            "class ",
            "public interface ",
            "interface "
        };
        
        for (String pattern : codeStartPatterns) {
            int index = cleaned.indexOf(pattern);
            if (index > 0 && index < 200) { // Only if pattern found within first 200 chars
                // Check if there's text before this pattern
                String beforePattern = cleaned.substring(0, index).trim();
                // If text before pattern doesn't look like code, remove it
                if (!beforePattern.contains("{") && !beforePattern.contains(";")) {
                    cleaned = cleaned.substring(index);
                    break;
                }
            }
        }
        
        // Case 4: Remove trailing explanatory text after code
        // Look for common ending patterns
        String[] endPatterns = {
            "\n\nExplanation:",
            "\n\nNote:",
            "\n\nLưu ý:",
            "\n\nGiải thích:"
        };
        
        for (String endPattern : endPatterns) {
            int index = cleaned.indexOf(endPattern);
            if (index != -1) {
                cleaned = cleaned.substring(0, index);
                break;
            }
        }
        
        cleaned = cleaned.trim();
        
        if (cleaned.isEmpty()) {
            throw new IOException("ResponseParser extractCodeFromResponse: Code is empty after extraction");
        }
        
        return cleaned;
    }
    
    /**
     * Check xem string có phải là valid JSON không.
     */
    private static boolean isValidJson(String text) {
        if (text == null || text.isBlank()) {
            return false;
        }
        
        try {
            mapper.readTree(text);
            return true;
        } catch (Exception e) {
            return false;
        }
    }
    
    /**
     * Try to recover a truncated JSON array by finding the last complete object.
     * When AI hits max_tokens, JSON gets cut mid-string. This method finds the
     * last complete "}" and closes the array with "]".
     * 
     * Example: "[{...}, {...}, {\"input\": \"1 0 1 0 1 0" → "[{...}, {...]"
     * 
     * @param truncatedJson the truncated JSON string
     * @return recovered valid JSON string, or null if recovery failed
     */
    private static String tryRecoverTruncatedJsonArray(String truncatedJson) {
        if (truncatedJson == null || !truncatedJson.trim().startsWith("[")) {
            return null;
        }
        
        // Find the last complete JSON object boundary
        // We look for "},\n" or "}\n" patterns that indicate end of a complete object
        int lastCompleteObj = -1;
        int depth = 0;
        boolean inString = false;
        boolean escaped = false;
        
        for (int i = 0; i < truncatedJson.length(); i++) {
            char c = truncatedJson.charAt(i);
            
            if (escaped) {
                escaped = false;
                continue;
            }
            
            if (c == '\\') {
                escaped = true;
                continue;
            }
            
            if (c == '"') {
                inString = !inString;
                continue;
            }
            
            if (inString) continue;
            
            if (c == '{' || c == '[') {
                depth++;
            } else if (c == '}' || c == ']') {
                depth--;
                // depth == 1 means we just closed a top-level object inside the array
                if (depth == 1 && c == '}') {
                    lastCompleteObj = i;
                }
            }
        }
        
        if (lastCompleteObj > 0) {
            String recovered = truncatedJson.substring(0, lastCompleteObj + 1) + "\n]";
            System.err.println("=== DEBUG: Recovered JSON by truncating at position " + lastCompleteObj + 
                             " (original length: " + truncatedJson.length() + ") ===");
            return recovered;
        }
        
        return null;
    }
    
    /**
     * Get string field từ JsonNode, thử nhiều tên field khác nhau.
     * Trả về null nếu không tìm thấy field nào.
     */
    private static String getStringField(JsonNode node, String... fieldNames) {
        for (String fieldName : fieldNames) {
            if (node.has(fieldName)) {
                JsonNode fieldNode = node.get(fieldName);
                if (!fieldNode.isNull()) {
                    return fieldNode.asText();
                }
            }
        }
        return null;
    }
    
    /**
     * Extract explanation từ comments trong code.
     * Tìm comment có chứa WA:, TLE:, hoặc AC: để làm explanation.
     */
    private static String extractExplanationFromCode(String code, SampleCode.CodeType type) {
        String[] lines = code.split("\n");
        
        String marker = switch (type) {
            case WA -> "// WA:";
            case TLE -> "// TLE:";
            case AC -> "// AC:";
        };
        
        for (String line : lines) {
            String trimmed = line.trim();
            if (trimmed.startsWith(marker)) {
                return trimmed.substring(marker.length()).trim();
            }
        }
        
        return null;
    }
    
    // ===== 5. PARSE MULTIPLE CODES (BATCH) =====
    
    /**
     * Parse response chứa nhiều code (AC, WA, TLE) được phân cách bằng ===TYPE===.
     * 
     * Format response từ AI:
     * ===AC===
     * #include <iostream>
     * ...
     * 
     * ===WA===
     * #include <iostream>
     * ...
     * 
     * ===TLE===
     * #include <iostream>
     * ...
     * 
     * @param response raw response từ AI
     * @param language ngôn ngữ lập trình
     * @return Map<CodeType, String> - map từ loại code sang source code
     * @throws IOException nếu không parse được
     */
    public static java.util.Map<SampleCode.CodeType, String> parseMultipleCodes(String response, 
                                                                                  SampleCode.Language language) throws IOException {
        if (response == null || response.isBlank()) {
            throw new IOException("ResponseParser parseMultipleCodes: Response is empty");
        }
        
        java.util.Map<SampleCode.CodeType, String> result = new java.util.HashMap<>();
        
        // Remove markdown code blocks nếu có
        String cleaned = response.trim();
        if (cleaned.contains("```")) {
            int firstBacktick = cleaned.indexOf("```");
            int lastBacktick = cleaned.lastIndexOf("```");
            
            if (firstBacktick != -1 && lastBacktick != -1 && firstBacktick < lastBacktick) {
                String betweenBackticks = cleaned.substring(firstBacktick + 3, lastBacktick);
                
                // Remove language identifier
                betweenBackticks = betweenBackticks.trim();
                if (betweenBackticks.startsWith("cpp") || betweenBackticks.startsWith("c++")) {
                    int firstNewline = betweenBackticks.indexOf('\n');
                    if (firstNewline != -1) {
                        betweenBackticks = betweenBackticks.substring(firstNewline + 1);
                    }
                }
                
                cleaned = betweenBackticks.trim();
            }
        }
        
        // Tìm các marker ===AC===, ===WA===, ===TLE===
        String[] markers = {"===AC===", "===WA===", "===TLE==="};
        SampleCode.CodeType[] types = {SampleCode.CodeType.AC, SampleCode.CodeType.WA, SampleCode.CodeType.TLE};
        
        for (int i = 0; i < markers.length; i++) {
            String marker = markers[i];
            SampleCode.CodeType type = types[i];
            
            int markerIndex = cleaned.indexOf(marker);
            if (markerIndex == -1) {
                // Marker không tìm thấy, skip
                continue;
            }
            
            // Tìm vị trí bắt đầu code (sau marker)
            int codeStart = markerIndex + marker.length();
            
            // Tìm vị trí kết thúc code (trước marker tiếp theo hoặc cuối string)
            int codeEnd = cleaned.length();
            for (int j = 0; j < markers.length; j++) {
                if (i != j) { // Không tìm chính marker hiện tại
                    int nextMarkerIndex = cleaned.indexOf(markers[j], codeStart);
                    if (nextMarkerIndex != -1 && nextMarkerIndex < codeEnd) {
                        codeEnd = nextMarkerIndex;
                    }
                }
            }
            
            // Extract code
            String code = cleaned.substring(codeStart, codeEnd).trim();
            
            // Validate code không rỗng
            if (code.isEmpty()) {
                throw new IOException("ResponseParser parseMultipleCodes: Code for " + type + " is empty");
            }
            
            // Validate code có cấu trúc cơ bản
            if (!code.contains("#include") && !code.contains("int main")) {
                throw new IOException("ResponseParser parseMultipleCodes: Code for " + type + 
                                      " is invalid - missing #include or main function");
            }
            
            result.put(type, code);
        }
        
        // Validate ít nhất có 1 code
        if (result.isEmpty()) {
            throw new IOException("ResponseParser parseMultipleCodes: No code found in response. " +
                                  "Expected markers: ===AC===, ===WA===, ===TLE===");
        }
        
        return result;
    }
}
